name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write   # needed to push tags and update releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # semantic-release needs full history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'  # >= 20.8.1 required

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.Terraform_Repo_Token}}  # built-in token from Actions
        run: npx semantic-release
